---
title: "Using Python within Linux"
author: "Jan Verbesselt"
date: "22 Jan 2015"
output: slidy_presentation
---

## Session of yesterday


* Github page is forked to the GitHub Geo-scriptin @ WUR group
    * https://github.com/divisionblue/wur-python
    * Presentation is available here: http://divisionblue.github.io/wur-python/
    * http://geojson.org/geojson-spec.html

## Tuning the terminal

http://www.drbunsen.org/the-text-triumvirate/

Look for the following plugins to tune your `terminal`:

*  TMUX: http://tmux.sourceforge.net/
*  [Powerline](http://computers.tutsplus.com/tutorials/getting-spiffy-with-powerline--cms-20740)

## Some questions

* What do you remember from yesterday?
* Can you answer the questions that have been asked in the questionnaire this morning?

Fill in the following sheet per team:

* http://goo.gl/forms/xv7Chgkq97


## Today's presentation

By [Jorge Mendes de Jesus](http://www.isric.org/users/jorge-mendes-de-jesus) from ISRIC:

* Jorge is a scientifical programmer with a background in open source GIS and python development.
* [Presentation about Why Python geo-spatial things?](https://docs.google.com/presentation/d/1IkeUUArTIjQNuKLP43p-vXdazqtMaVEzlFCd2nLnrdY/edit?usp=sharing)

## A nice meeting

FOSDEM is a free and non-commercial event organised by the community for
the community. The goal is to provide open source software developers
and communities a place to meet. Participation and attendance is totally
free, though the organisers gratefully accept donations and sponsorship.
https://fosdem.org/

http://www.osgeo.org/node/1464

## Python

Who has done the `Python` refresher?

```{r, engine='python'}
import this
```


<!---
framework: shower
highlighter: tomorrow
-->